name: Continuous Integration

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Build Docker Image
        run: docker build -t my-app-image .

      - name: Run Docker Container
        run: docker run --name my-app-container -d -p 3000:3000 my-app-image

      - name: Check if the container is running
        run: docker ps | grep my-app-container

      - name: Test HTTP Request
        run: curl --fail http://localhost:3000
